### ISSUE TITLE
first login works, second fails

### ISSUE THREAD

**Issue by j2l** [totaljs/hello#2]
Install locally
create a user, you're logged-in.
Clear cookies, refresh, re-enter same credentials:
`Your token is invalid, review it on platform.totaljs.com`

**Comment by petersirka** [comment]
Hi @j2l,
You forgot to enter the Total.js API key (you must remove the /databases/ folder or update /databases/preferences.json by adding the Total.js API key). It's needed because our API sends verification code to the user's e-mail address. You can easily create an API key at https://platform.totaljs.com --> section --> API Services (pricing list: https://docs.totaljs.com/totalapi/). If you don't want to pay for sending emails, you can easily rewrite app behaviour. One e-mail costs 0.02 EUR and the session is valid for one month.

BTW: If you create a Total.js API key, you will receive 0.25 EUR for testing. 

![20230519-115023](https://github.com/totaljs/hello/assets/2414252/5a3f9e53-c24d-49eb-ab2e-b9a95c488f61)

I have tested the app and it works.
Thank you

**Comment by j2l** [comment]
OK. Thank you for the prompt and detailed reply.
Email used was qw@qw.qw so it's sure it can't be validated :) and don't need to be actually.
Would you please explain how to bypass email validation so it could be tested without internet?

**Comment by petersirka** [comment]
In this case you need to update the source code. I have updated it a bit, so you can sign-in without sending email (it's dangerous, but it can solve your problem :-D). I have then downloaded all the dependencies, so the app below will work without internet access.

- download app [hello.zip](https://github.com/totaljs/hello/files/11517300/hello.zip)

**Comment by j2l** [comment]
Thank you very much @petersirka it works fine locally.
Do you know a tutorial about building with AppBuilder from scratch?

**Comment by Invincible83** [comment]
As far I know, there isn't @j2l
